name: $(Year:yy)$(DayOfYear).$(rev:r)
trigger:
  branches:
    include: [master]
  paths:
    include:
      - 'dotnet-roslyn/analyzers/Audacia.CodeAnalysis.Analyzers/*'
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { vmImage: windows-latest }

stages:
- stage: Build
  displayName: Build
  jobs:
    - template: src/build/dotnet/jobs/nuget-package.job.yaml@templates
      parameters:
        projects: 'dotnet-roslyn/analyzers/Audacia.CodeAnalysis.Analyzers/src/Audacia.CodeAnalysis.Analyzers/Audacia.CodeAnalysis.Analyzers.csproj'
        tests: 'dotnet-roslyn/analyzers/Audacia.CodeAnalysis.Analyzers/tests/Audacia.CodeAnalysis.Analyzers.Test/Audacia.CodeAnalysis.Analyzers.Test.csproj'

- stage: Release
  displayName: Release
  jobs:
    - template: src/deployment/nuget/jobs/internal-public-nuget-package.job.yaml@templates
      parameters:
        environment: NuGet Internal (Gated)
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))